export enum Dialog {
  CONFIRM_ACTION = 'CONFIRM_ACTION',
  CREATE_CHANNEL = 'CREATE_CHANNEL',
  TEXT_INPUT = 'TEXT_INPUT',
  SERVER_PASSWORD = 'SERVER_PASSWORD',
  CHANGE_ROLE = 'CHANGE_ROLE',
  CREATE_INVITE = 'CREATE_INVITE',
  CREATE_CATEGORY = 'CREATE_CATEGORY'
}
